CHROME_DRIVER_PATH: "PATH TO CHROME DRIVER, e.g.: ./chromedriver"
CHROME_DOWNLOAD_FOLDER: "PATH to DOWNLOAD FOLDER, e.g.: ./Downloads/"
GOOGLE_CREDENTIALS_JSON: "./credentials.json"
GOOGLE_TOKEN_NAME: "token_for_rpa.pickle"
GOOGLE_SCOPES:
  - "https://www.googleapis.com/auth/drive"
  - "https://www.googleapis.com/auth/spreadsheets"
  - "https://www.googleapis.com/auth/gmail.readonly"
NETI_LOGIN_URL: "LOGIN URL FRO YOUR NETI CRM, e.g.: https://xxx.neticrm.tw/user/login"
NETI_ACCOUNT_NAME: "NETI ACCOUNT NAME"
NETI_ACCOUNT_PASWD: "NETI ACCOUNT PASSWORD"
SHEET_RANGE: "Response!A1:K3"
SHEET_ID: "SHEET ID, e.g.: 20ZSW4IXuKxGjGdaG5aLeVSf_0pgbeukax1Hh0l8q9RQ"
CERTIFICATE_FOLDER: "CERTIFICATE UPLOAD FOLDER, e.g.: 9iLzvVub8H7l47nkfLXox-Czylhekri4c"
